//LOGIN
export const SAVE_LOGIN = 'save_login'
export const SAVE_USER = 'save_user'
export const SAVE_REGISTER = 'save_register'
export const SAVE_CATEGORY_LIST = 'save_category_list'
export const SAVE_TOKEN = 'save_token'
export const SAVE_PERSISTENT_DATA = 'SAVE_PERSISTENT_DATA'
export const SAVE_STATUS_LOCATION = 'SAVE_STATUS_LOCATION'
export const SAVE_PERMISION_QUESTION_DONE = 'SAVE_PERMISION_QUESTION_DONE'
export const SAVE_CLOSING_SESSION = 'SAVE_CLOSING_SESSION'

//CART
export const ADD_CART = 'add_cart'

//BUSINESS
export const COLLECT_TRANSBUS = 'COLLECT_TRANSBUS';
export const SELECTED_BUSWALLET = 'SELECTED_BUSWALLET';
export const GET_DATA_BUSWALLET = 'GET_DATA_BUSWALLET';
export const ACT_BUSWALLET = 'ACT_BUSWALLET';
export const GET_BUSINESS = 'get_business'
export const LOADING_GET_BUSINESS = 'loading_get_business'
export const GET_BUSINESS_EMPTY = 'GET_BUSINESS_EMPTY'
export const RESET_BUSINESS = 'RESET_BUSINESs'
export const GET_CATEGORIES_FULL = 'GET_CATEGORIES_FULL'
export const GET_CATEGORIES_ADMIN = 'GET_CATEGORIES_ADMIN'
export const LOADING_GET_CATEGORIES_FULL = 'loading_get_categories_full'
export const GET_CATEGORIES_ONLY_STORE = 'GET_CATEGORIES_ONLY_STORE'
export const LOADING_GET_CATEGORIES_ONLY_STORE = 'LOADING_GET_CATEGORIES_ONLY_STORE'
export const GET_ICONS = 'GET_ICONS'
export const GET_STORE_INFO = 'GET_STORE_INFO'
export const LOADING_GET_STORE_INFO = 'LOADING_GET_STORE_INFO'
export const ADDRESS_STORE_FORM = 'ADDRESS_STORE_FORM'
export const INITIAL_ROUTER_BUSINNES = 'INITIAL_ROUTER_BUSINNES'
export const PARAMS_BUSINESS_INPREPARATIONDETAIL = 'PARAMS_BUSINESS_INPREPARATIONDETAIL'
export const UNMOUNT_BUSINNES_STACK = 'UNMOUNT_BUSINNES_STACK'
export const DATA_DAYS_ATTE_SCHEDULE = 'DATA_DAYS_ATTE_SCHEDULE'
export const DATA_DAYS_DELIVERY_SCHEDULE = 'DATA_DAYS_DELIVERY_SCHEDULE'
export const DATA_DAYS_SPECIAL_SCHEDULE = 'DATA_DAYS_SPECIAL_SCHEDULE'
export const UPDATE_LIST_ORDER = 'UPDATE_LIST_ORDER'
//SHOPHOME
export const GET_CATEGORIES_GROUP = 'get_categories'
export const GET_CATEGORIES_GROUP_LOADING = 'sget_categories_loading'
export const SAVE_SHOPS_PARAMS = 'SAVE_SHOPS_PARAMS'
export const GET_FULLCATS_BY_STORE = 'GET_FULLCATS_BY_STORE'
export const GET_FULLCATS_BY_STORE_LOADING = "GET_FULLCATS_BY_STORE_LOADING"

export const GET_ORDERS_BY_USER = 'GET_ORDERS_BY_USER'
export const LOADING_GET_ORDERS_BY_USER = 'LOADING_GET_ORDERS_BY_USER'

export const GET_WALLET_BY_USER = "GET_WALLET_BY_USER"
export const INITIAL_ROUTER_SHOP_HOME = "INITIAL_ROUTER_SHOP_HOME"
export const PARAMS_STORESALES_PRODUCTS_SHOP = "PARAMS_STORESALES_PRODUCTS_SHOP"

//DELIVERY
export const REGION_COORDS = 'REGION_COORDS'
export const ADDRESS_DELIVERY = 'ADDRESS_DELIVERY'
export const PRODUCT_SALES = 'PRODUCT_SALES'
export const STORE_DELIVERY = 'STORE_DELIVERY'
export const PAYMENT_DATA = 'PAYMENT_DATA'
export const TOTAL_DELIVERY = 'TOTAL_DELIVERY'
export const CURRENT_ID_DELIVERY = 'CURRENT_ID_DELIVERY'
export const EMPLOYEE_DATA = 'EMPLOYEE_DATA'
export const SAVE_LAST_DELIVERY = 'SAVE_LAST_DELIVERY'
export const START_ADDRESS = 'START_ADDRESS'
export const START_ADDRESSDELIVERY = 'START_ADDRESSDELIVERY'
export const SAVE_SCHEDULE = 'SAVE_SCHEDULE'
export const SAVE_SEARCH_RADIUS = 'SAVE_SEARCH_RADIUS'
export const SAVE_SOCKET_1 = 'SAVE_SOCKET_1'

//LAST CREEN
export const LAST_SCREEN = 'last_screen'

//WALLETS
export const ACT_WALLET = 'ACT_WALLET';
export const GET_CASH_BY_USER = 'GET_CASH_BY_USER';
export const VERIF_WALLET = 'VERIF_WALLET';
export const SELECTED_WALLET = 'SELECTED_WALLET';
export const COLLECT_TRANS = 'COLLECT_TRANS';

//NOTIFICATION
export const SAVE_ONE_NOTIFICATION = 'SAVE_ONE_NOTIFICATION';
export const SAVE_COUNT_NOTIF = 'SAVE_COUNT_NOTIF';
export const SAVE_FULL_NOTIFICATION = 'SAVE_FULL_NOTIFICATION';
export const SAVE_FIRETOKEN_NOTIFICATION = 'SAVE_FIRETOKEN_NOTIFICATION';


// KDRIVERS
export const GET_KDRIVVER_STATUS = 'GET_KDRIVVER_STATUS'
export const KDRIVER_CURRENT_POSITION = 'KDRIVER_CURRENT_POSITION'
export const BACKGROUND_TWO_KDRIVER = 'BACKGROUND_TWO_KDRIVER'


// ORDERS
export const GET_ORDER_ST = 'GET_ORDER_ST'
export const SET_ORDER_ID = 'SET_ORDER_ID'
export const ACT_ST_ORDER = 'ACT_ST_ORDER';
export const FLOW_ST_ORDER = 'FLOW_ST_ORDER';

